src/config/routes.rb
CodeSwap::Application.routes.draw do
  get "admin/index"

  resources :file_submissions
  resources :authentications
  resources :user
  devise_for :users, :controllers => { :registrations => 'registrations'}

  get "home/index"

  match 'contact_us', :controller => 'home', :action => 'contact_us', :as => 'contact_us'
  match 'send_contact_email', :controller => 'home', :action => 'send_contact_email', :as => 'send_contact_email'

  root :to => "home#index"

  match '/auth/:provider/callback' => 'authentications#create'

  match '/users/sign_up' => 'home#index'

  match "admin/create_faculty", :controller => 'admin', :action => 'create_faculty'
  match 'admin', :controller => 'admin', :action => 'index', :as => 'admin_path'
  match 'users', :controller => 'admin', :action => 'index', :as => 'view_users'
  match 'admin/add_user', :controller => 'admin', :action => 'add_user'
  match 'view_faculty', :controller => 'admin', :action => 'view_faculty', :as => 'view_faculty'
  match 'view_admin', :controller => 'admin', :action => 'view_admin', :as => 'view_admin'
  match 'view_students', :controller => 'admin', :action => 'view_students', :as => 'view_students'
  match 'admin/delete_user', :controller => 'admin', :action => 'delete_user'
  match 'admin/search_users', :controller => 'admin', :action => 'search_users', :as => 'search_users'
  match 'admin/view_user_info', :controller => 'admin', :action => 'view_user_info', :as => 'view_user_info'
  match 'admin/recent_activity', :controller => 'admin', :action => 'view_recent_activity'

  # Faculty // Course Routes

  match 'course/show/:c_id', :controller => 'course', :action=>'show', :as => 'show_course'
  match 'course/edit/:id', :controller => 'course', :action => 'edit', :as => 'edit_course'
  match 'course/submit_edit', :controller => 'course', :action => 'submit_edit'
  match 'course/manage_groups/:id', :controller => 'course', :action => 'manage_groups'
  get "faculty/index"
  match 'faculty/index', :controller => 'faculty', :action => 'index', :as => 'faculty_index'
  match '/courses', :controller => 'faculty', :action => 'index', :as => 'course_index'
  match 'course/new', :controller => 'course', :action => 'new', :as => 'new_course'
  match 'course/create', :controller => 'course', :action => 'create', :as => 'create_course'
  match 'course/add_student', :controller => 'course', :action => 'add_student'
  
  # Assignment Routes
  get "assignment/index"
  match 'assignment', :controller => 'assignment', :action=> 'index'
  match 'assignments', :controller => 'assignment', :action=> 'index'
  match 'assignment/create/:course_id', :controller => 'assignment', :action => 'create' 
  match 'assignment/edit/:assignment_id', :controller => 'assignment', :action => 'edit' 
	match 'assignment/view/:assignment_id',:controller => 'assignment', :action => 'view', :as => 'assignment_view'
  match 'assignment/submit_new', :controller => 'assignment', :action => 'submit_new'
  match 'assignment/submitchanges', :controller =>'assignment', :action => 'submitchanges'
  match 'assignment/upload', :controller => 'assignment', :action => 'upload'
  match 'assignment/adminView/:assignment_id', :controller => 'assignment', :action => 'adminView'
  match 'assignment/download/:file_id', :controller => 'assignment', :action => 'download'
  match 'assignment/downloadAll/:assignment_id', :controller => 'assignment', :action => 'downloadAll'

  # Review Assignment Routes
  match 'reviewassignment/create/:assignment_id',:controller => 'review_assignment', :action => 'create'
  match 'reviewassignment/pairings',:controller => 'review_assignment', :action => 'pairings'
  match 'reviewassignment/pairings/:redo',:controller => 'review_assignment', :action => 'pairings'
  match 'reviewassignment/view/:id',:controller => 'review_assignment', :action => 'view'
  match 'reviewassignment/studentsubmit',:controller => 'review_assignment', :action => 'student_submit'
  match 'reviewassignment/viewsubmission/:mapping_id',:controller => 'review_assignment', :action => 'view_submission'
	match 'reviewassignment/:id/grades',:controller => 'review_assignment', :action => 'grades'
	match 'reviewassignment/:id/:pos/answer_form',:controller => 'review_assignment', :action => 'answer_form'
  match 'reviewassignment/edit/:id', :controller => 'review_assignment', :action => 'edit'
  match 'reviewassignment/view_feedback/:id' => 'review_assignment#view_feedback'
  match 'reviewassignment/submit_faculty_review/' => 'review_assignment#submit_faculty_review'
  
  # File Routes
  match 'files/delete/:file_id', :controller => 'file_submissions', :action => 'delete', :as => 'remove_file'
  match 'view_live/:file_id', :controller => 'file_submissions', :action => 'view_live', :as => 'view_live'


  #Redirect to 404 Page
  #This MUST be the last route
  match '*a', :to => 'errors#routing'
end

src/app/models/course.rb
class Course < ActiveRecord::Base
  require 'csv'

  belongs_to :user
  has_one :student_in_course
  has_one :ta_for_course
	has_many :course_groups
  attr_accessible :course_number, :name, :section, :term, :user_id

  # Imports Students / TAs from a spreadsheet
	# [Input]
	## * file -- a file in CSV format that contains the following information (with headers)
	##     1. first_name
	##     2. last_name
	##     3. email
	##     4. role (student,ta)
	##     5. group (1,2)
	# [Note]
	## * Creates accounts for users that were not in the database, sends them a registration email
	## * Groups should be even in size (if possible)
  def import_students_and_tas(file)
      spreadsheet = open_spreadsheet(file)
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        user = User.find_by_email(row["email"].downcase)
        # Create random password, requires members to respond to email before using the system.
        unless user
          o =[('a'..'z'),('A'..'Z'),('0'..'9')].map{|i| i.to_a}.flatten
          token = (0...12).map{ o[rand(o.length)] }.join
          user = User.new(:password => token, :password_confirmation => token)
          user.reset_password_token = token
          user.reset_password_sent_at = Time.now
          user.attributes = row.to_hash.slice(*User.accessible_attributes)
          user.role = 'student'
          user.save!
          Emailer.delay.signup_confirmation(user)
        end

        if row["role"].downcase == 'student'
          StudentInCourse.create(:user_id =>  user.id, :course_id => id)
					group = row['group']
					unless(group.nil?)
						CourseGroup.create(:user_id => user.id, :course_id => id, :group => group)
					end
        elsif row["role"].downcase == 'ta'
          TaForCourse.create(:user_id => user.id, :course_id => id)
        end
      end
  end

  # Fetches students within a course
	# [Return]
	## * Array of user_ids
  def get_students
    StudentInCourse.where(:course_id => id).collect(&:user_id)
  end


  # Fetches teaching assistants within a course
	# [Return]
	## * Array of user_id
  def get_tas
    TaForCourse.find_all_by_course_id(id).collect(&:user_id)
  end
	
	# Checks if a user is a TA for the course
	# [Input]
	## * user_id -- user_id to check
	# [Return]
	## * True if the user is a ta, false otherwise
  def is_user_ta(user_id)
    get_tas.include?(user_id)
  end
    
  def is_user_student(user_id)
    get_students.include?(user_id)
  end

  # Helper used to open CSV / Excel files
	# [Input]
	## * file -- file to be opened
	# [Return]
	## * Readable file object if the file is a csv, xls, or xlsx, redirects otherwise
  def open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else 
      flash[:error] = "Unknown file type: #{file.original_filename}"
      redirect_to new_course_path
    end
  end

  # Get the different student groups (group 1 and 2)
	# [Return]
	## * 2D array of user_ids
	def get_groups
		group0 = course_groups.find_all_by_group(0).collect(&:user_id)
		group1 = course_groups.find_all_by_group(1).collect(&:user_id)
		[group0,group1]
	end

end

src/app/controllers/course_controller.rb
# TODO: Email Notifications for Administrators
## Handles Course Views
class CourseController < ApplicationController
include CourseHelper

  ## Displays information about the course
  # [Route(s)]
  ## * /course/show/:c_id
  # [Params]
  ## * c_id - id for the course
  # [Environment Variables]
  ## [course]
  ### * Current course to be viewed
  ## [students]
  ### * List of students in the course
  ## [tas]
  ### * List of tas in the course
  ## [teacher]
  ### * Faculty member for the course
  ## [admin]
  ### * List of all admins
  ## [user_is_student]
  ## [user_is_ta_or_faculty_or_admin]
  ## [group1]
  ### * Users belonging to Group 1 for the course
  ## [group2]
  ### * Users belonging to Group 2 for the course
  ## [assignments]
  ### * All regular assignments for the course
  ## [review_assignments]
  ### * All review assignments for the course
  def show
    id = params[:c_id]
		logger = Logger.new('log/course.log')
		logger.info params.inspect
    @course = Course.find(id)    
    requires({'role' => ['admin','faculty','student'],'course_id' => id})
		#if the course is found & and the user is enrolled in the course, retrieve mappings of students and tas to a course.
    unless (@course.nil? || current_user.nil?)
      @students = StudentInCourse.where(:course_id => id)
      @tas = TaForCourse.where(:course_id => id)
      @teacher = User.where(:id => @course.user_id).first
      @admin = User.where(:role => 'admin')
			#Detect whether user is student or faculty for this given course (can't use roles due to TAs)
      @user_is_student = !@students.find_all_by_user_id(current_user.id).empty?
      @user_is_ta_or_faculty_or_admin = !@tas.find_all_by_user_id(current_user.id).empty? || (current_user.id == @teacher.id unless @teacher.nil?) || (@admin.include?(current_user) unless @admin.nil?)
      if(@user_is_student)
        @assignments = Assignment.where(:course_id => id, :hidden => false)
      else
        @assignments = Assignment.where(:course_id => id)
      end
      
      @group1 = CourseGroup.find_all_by_course_id_and_group(id, 0).collect(&:user_id)
      @group2 = CourseGroup.find_all_by_course_id_and_group(id, 1).collect(&:user_id)
      
			@review_assignments = ReviewAssignment.find_all_by_course_id(id)
    end
  end

  
  ## Populates view with modifiable course information
  # [Route(s)]
  ## * /course/edit/:id
  # [Params]
  ## * id - ID of the course to modify
  # [Environment Variables]
  ## * course - Course being modified
  ## * students - List of students in the course
  ## * tas - List of teaching assistants for the course
  def edit
    #Validate
    id = params[:id]
    @course = Course.find(id)
    requires({'role' => ['admin','faculty'],'course_id' => id})
    if(@course.nil?)
      flash[:error] = 'Something has gone horribly wrong. A system administrator has been contacted.'
    else
      student_ids = StudentInCourse.where(:course_id => id).collect(&:user_id)
      ta_ids = TaForCourse.where(:course_id => id).collect(&:user_id)
      
      @students = User.find_all_by_id(student_ids)
      @tas = User.find_all_by_id(ta_ids)
    end
  end

  ## Updates course information
  # [Route(s)]
  ## * /course/submit_edit/
  # [Params]
  ## * course_id - ID of course being modified
  ## * number - New Course Number of the course
  ## * term - New term of the course
  ## * section - New section of the course
  ## * name - New name of the course
  # [Environment Variables]
  ## * None
  def submit_edit
    id = params[:course_id]
    requires({'role' => ['admin','faculty'],'course_id'=>id})
    course_number = params[:number]
    course_term = params[:term]
    course_name = params[:name]
    course_section = params[:section]

    studentsToRemove = params[:students_to_remove]
    tasToRemove = params[:tas_to_remove]

    course = Course.find(id)
    


    course.course_number = course_number
    course.term = course_term
    course.name = course_name
    course.section = course_section
    course.save
    
    StudentInCourse.delete_all(:course_id => id, :user_id => studentsToRemove)
    TaForCourse.delete_all(:course_id => id, :user_id => tasToRemove)

    flash[:notice] = "Changes saved."
  
  end

  ## Populates a view for creating a new course
  # [Route(s)]
  ## * /course/new
  # [Params]
  ## * None
  # [Environment Variables]
  ## * None
  def new
    requires({'role' => ['admin','faculty']})
  end

  ## Creates a new course with info from /new page
  # [Route(s)]
  ## * /course/create
  # [Params]
  ## * course_name - Name of the course
  ## * course_term - Term of the course
  ## * course_number - Course Number of the course
  ## * students_csv - .csv of the students file
  # [Environment Variables]
  ## * None
  def create
    requires({'role' => ['admin','faculty']})
    course_name = params[:course_name]
    course_term = params[:course_term]
    course_number = params[:course_number]
    course_section = params[:course_section]

    course_exists = !(Course.find_all_by_name_and_course_number_and_section_and_term(course_name, course_number, course_section, course_term).empty?)

    if course_exists
      flash[:error] = 'A course already exists with that information. Please try again with new info or contact a system administrator.'
      redirect_to new_course_path(:name => course_name, :term => course_term, :number => course_number, :section => course_section)
    else
      course = Course.create(:name => course_name, :course_number => course_number, :section => course_section, :term => course_term, :user_id => current_user.id)

      
      course.import_students_and_tas(params[:students_csv])
			course.save
      flash[:notice] = 'Course created successfully!'
      redirect_to show_course_path course.id
    end
  end

  ## Adds student (creates new user if it doesn't exist) to the course
  # [Route(s)]
  ## * /course/add_student
  # [Params]
  ## * course_id - ID of course the user is being added to
  ## * first - First name of the user
  ## * last - Last name of the user
  ## * email - Email address of the user
  ## * role - Role the user will have in the course (ta/student)
  # [Environment Variables]
  ## * None
  def add_student
    course_id = params[:course_id]
    requires({'role' => ['admin','faculty'],'course_id'=>course_id})
    first = params[:first]
    last = params[:last]
    email = params[:email]
    role = params[:role]
    
    
    course = Course.find(course_id)

    student = User.find_by_email(email)
    unless student
      student = create_and_invite_user(first, last, email, 'student')
    end

    unless student
      render :text => 'Error adding student.'
    else
      if role == 'student'
        StudentInCourse.create(:user_id => student.id, :course_id => course.id)
        render :text => 'Student added successfully.'
      elsif role == 'ta'
        TaForCourse.create(:user_id => student.id, :course_id => course.id)
        render :text => 'TA added successfully.'
      end
    end
  end

  ## Manages student groups for the given course
  # [Route(s)]
  ## * /course/manage_groups/id
  # [Params]
  ## * (GET) id - ID of the course
  ## * (POST) group1 - List of students in group 1
  ## * (POST) group2 - List of students in group 2
  ## * (POST) ungrouped - unused.
  # [Environment Variables]
  ## * (GET) ungrouped - List of students that do not belong to a group
  ## * (GET) group_1 - List of students belonging to group 1
  ## * (GET) group_2 - List of students belonging to group 2
  ## * (POST) None
  def manage_groups
  
    if request.get?
      course_id = params[:id]
      @course = Course.find(course_id)
      
      group_1 = CourseGroup.find_all_by_course_id_and_group(course_id, 0).collect(&:user_id)
      group_2 = CourseGroup.find_all_by_course_id_and_group(course_id, 1).collect(&:user_id)

      course_students = StudentInCourse.find_all_by_course_id(course_id).collect(&:user_id)
      
      @ungrouped = User.find_all_by_id(course_students).reject{ |user| user.id.in? group_1 or user.id.in? group_2 }
      @group_1 = User.find_all_by_id(group_1)
      @group_2 = User.find_all_by_id(group_2)
    else #post request
      course_id = params[:id]
      group1 = params['group1']
      group2 = params['group2']
      ungrouped = params['ungrouped']
      
      
      
      CourseGroup.destroy_all(:course_id => course_id)
      group1.each do |user|
        CourseGroup.create(:course_id => course_id, :user_id => user, :group => 0)
      end
      group2.each do |user|
        CourseGroup.create(:course_id => course_id, :user_id => user, :group => 1)
      end
      
      render :nothing => true
      flash[:notice] = "Groups updated!"
    end
  end
  

end

src/app/helpers/course_helper.rb
# EMPTY
module CourseHelper
include ApplicationHelper
end

src/app/views/course/edit.html.erb
<p id="course_id" style="display:none"><%= @course.id %></p>
<p><%= link_to "Home", root_url %> // <%= link_to "Courses", faculty_index_path %> // Edit Course</p>
<h1>Editing Course Information</h1>
<h4>Instructions:</h4>
<div class='well'>
<h5>Changing Course Information:</h5>
Click on any of the <strong>bold</strong> text below to edit the value.</br>
Be sure to click "Save Changes" when finished!</br>

<h5>Changing Course Roster:</h5>
<strong>Removing a student or TA</strong>
<ul>
  <li>Click show/hide roster</li>
  <li>Click "Remove" on the desired user's row</li>
  <li>Click "Save Changes" at the bottom of the page!</li>
</ul>
<strong>Adding a student or TA</strong>
<ul>
  <li>Click add student/TA</li>
  <li>Fill out relevant fields</li>
  <li>Be sure to specify Role field!</li>
  <li>Click Add when finished</li>
</ul>
</div>

<p>Editing Course: <strong id='course_name'><%= @course.name %></strong></p>

<p class='edit_course_info'>
  <ul>
    General Info:</br>
    <ul>
    <li>
      Section: <strong id='course_section'><%= @course.section %></strong>
    </t></li>

    <li>
      Term: <strong  id='course_term'><%= @course.term %></strong>
    </li>
    
    <li>
      Number: <strong id='course_number'><%= @course.course_number %></strong>  
    </li>
    </ul>
  </ul>

</p>

<p class='edit_course_students'>
    There are <strong><%= @students.count %></strong> students enrolled in the course. <t class='btn' id='toggle_students_button' onclick="$('#student_table').slideToggle('fast');">Show/Hide Student Roster</t>

  <table class='table table-hover' id='student_table' style='display:none'>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.id %></td>
          <td><%= student.friendly_full_name %></td>
          <td id="<%= student.id %>_enrolled">Enrolled</td>
          <td id="<%= student.id %>_add" style="display: none"><t class='btn' onclick="courses.edit.toggleStudent(<%=student.id%>);">Undo</t></td>
          <td id="<%=student.id %>_remove"><t class='btn btn-danger' onclick="courses.edit.toggleStudent(<%=student.id%>);">Remove</t></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<p class='edit_course_tas'>
    There are <strong><%= @tas.count %></strong> teaching assistants enrolled in the course. <t class='btn' onclick="$('#ta_table').slideToggle('fast');">Show/Hide TA Roster</t>

  <table class='table table-hover' id='ta_table' style='display:none'>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @tas.each do |ta| %>
        <tr>
          <td><%= ta.id %></td>
          <td><%= ta.friendly_full_name %></td>
          <td id="<%= ta.id %>_enrolled">Enrolled</td>
          <td id="<%= ta.id %>_add" style="display: none"><t class='btn' onclick="courses.edit.toggleTa(<%=ta.id%>);">Undo</t></td>
          <td id="<%= ta.id %>_remove"><t class='btn btn-danger' onclick="courses.edit.toggleTa(<%=ta.id%>);">Remove</t></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</p>

<p class='add_new_student'>
  <a class='btn' id='add_admin_button' onclick='$("#add_new_student").toggle("fast");'>Add New Student/TA</a>
  <form class="form-search" id='add_new_student' style='display:none'>
    <strong>First Name: </strong>
      <%= text_field_tag 'first_name', nil, :class => 'input-medium search-query', :placeholder => 'First Name' %>
    <strong>Last Name: </strong>
      <%= text_field_tag 'last_name', nil, :class => 'input-medium search-query', :placeholder => 'Last Name' %> 
    <strong>E-mail:</strong>  
      <%= text_field_tag 'email', nil, :class => 'input-medium search-query', :placeholder => 'email' %>
    <strong>Role:</strong>
      <%= select_tag 'role', options_for_select([['student', 'student'], ['teaching assistant', 'ta']]) %>
    <p class="btn" id='add_student_button'>Add</p>
  </form>
</p>

<p class='edit_course_submit'>
  <p class='btn' onclick='courses.edit.submit()'>Save Changes</p>
  <%= link_to 'Cancel', :back, :class => 'btn' %>
</p>


<script type='text/javascript'>
  $(document).ready(function() {
    courses.edit.pageLoad();
  });
</script>

src/app/views/course/manage_groups.html.erb
<h2> Managing Groups for <%= @course.name %> </h2>

<strong>Instructions</strong>: Drag and drop students into the desired groupings.</br>
<strong>IMPORTANT!</strong> The groups must be balanced (or differ by at most one student) if you wish to use this feature when creating swap assignments.</br>
<strong>ALSO IMPORTANT!</strong> Modifying these groups after a Review Assignment has been created and LINKING to this Assignment when making a new one MAY cause interesting results. Do so at your own risk.</br>

<h3> Group One </h3>
<strong>Note</strong>: During a Swap Assignment, the students in this group will be paired with <strong>Group One</strong> students.
<table class='table table-hover'>  
  <tbody id='group1' class='groupTable'>
  <tr class='sort-disabled' ><td><strong>Name</strong></td></tr>
<% @group_1.each do |user| %>
  <tr id = "<%= user.id %>" class='user-row'>
    <td><%= user.friendly_full_name %><td>
  </tr>
<% end %>
  </tbody>
</table>

<h3> Group Two </h3>
<strong>Note</strong>: During a Swap Assignment, the students in this group will be paired with <strong>Group One</strong> students.
<table class='table table-hover'> 
  <tbody id='group2' class='groupTable'>
  <tr class='sort-disabled' ><th><strong>Name</strong></th></tr>
<% @group_2.each do |user| %>
  <tr id="<%= user.id %>" class='user-row'>
    <td><%= user.friendly_full_name %><td>
  </tr>
<% end %>
  </tbody>
</table>


<h3> Ungrouped Students </h3>
<strong>Note</strong>: During a Swap Assignment, these students will be <strong>ignored</strong> if you choose to Swap based on Groups.
<table class='table table-hover'> 
  <tbody id='ungrouped' class='groupTable'>
  <tr class='sort-disabled' ><td><strong>Name</strong></td></tr>
    <% @ungrouped.each do |user| %>
    <tr id = "<%= user.id %>" class='user-row'>
      <td><%= user.friendly_full_name %><td>
    </tr>
  <% end %>
  </tbody>
</table>

<p class='btn' onclick="courses.groups.submit(<%= @course.id.to_s %>)">Submit Changes</p>
<a class='btn' href=<%= '/course/show/' + @course.id.to_s %>>Cancel</a>


<script>
  courses.groups.pageLoad();
</script>

src/app/views/course/new.html.erb
<!DOCTYPE html>


<p xmlns="http://www.w3.org/1999/html"><%= link_to "Home", root_url %> // <%= link_to "Courses", faculty_index_path %> // Add Course</p>



<div id = 'form1'>
<h1>New Course</h1>

<%= form_tag create_course_path, :id => 'add_students', :class => 'form-search', :multipart => true do %>
    <p>Add the basic class information here</p></br>
             <h4><strong>Course Number:</strong></h4>
                <%= text_field_tag 'course_number', @number, :class => 'input-medium search-query' %><p id='course_number_errors'/>
             <h4><strong>Course Name:</strong>  </h4>
                <%= text_field_tag 'course_name', @name, :class => 'input-medium search-query' %><p id='course_name_errors'/>
             <h4><strong>Course Section:</strong></h4> 
                <%= number_field_tag 'course_section', @section, :class => 'input-medium search-query', :in => 1..100 %><p id='course_section_errors'/>
            <h4><strong>Course Term:</strong></h4>
                <%= text_field_tag 'course_term', @term, :class => 'input-medium search-query' %><p id='course_term_errors'/>
<br/>

    <p>Upload a .csv file with student and TA information here. New student accounts will be created automatically if the student is not already registered on CodeSwap. </br>
    (Please <%= link_to 'Download The Template', '/template.csv', :class => 'btn' %> for formatting. Groups are 0 and 1. )</p>
    
    <%= file_field_tag :students_csv %>
    <p id='csv_errors'/>

    <p id='create_course_confirm' class='btn' onclick='courses.new.toggleSubmit();'>Create Course</p>

    <p id='create_course_submit' style='display:none'>
      A new course will be created.
      <%= submit_tag "Confirm", :class => 'btn' %>
      <t class='btn' onclick='courses.new.toggleSubmit();'>Cancel</t>
    </p>
    

<% end %>

<script type='text/javascript'>

  

</script>


</div>