src/config/routes.rb
CodeSwap::Application.routes.draw do
  get "admin/index"

  resources :file_submissions
  resources :authentications
  resources :user
  devise_for :users, :controllers => { :registrations => 'registrations'}

  get "home/index"

  match 'contact_us', :controller => 'home', :action => 'contact_us', :as => 'contact_us'
  match 'send_contact_email', :controller => 'home', :action => 'send_contact_email', :as => 'send_contact_email'

  root :to => "home#index"

  match '/auth/:provider/callback' => 'authentications#create'

  match '/users/sign_up' => 'home#index'

  match "admin/create_faculty", :controller => 'admin', :action => 'create_faculty'
  match 'admin', :controller => 'admin', :action => 'index', :as => 'admin_path'
  match 'users', :controller => 'admin', :action => 'index', :as => 'view_users'
  match 'admin/add_user', :controller => 'admin', :action => 'add_user'
  match 'view_faculty', :controller => 'admin', :action => 'view_faculty', :as => 'view_faculty'
  match 'view_admin', :controller => 'admin', :action => 'view_admin', :as => 'view_admin'
  match 'view_students', :controller => 'admin', :action => 'view_students', :as => 'view_students'
  match 'admin/delete_user', :controller => 'admin', :action => 'delete_user'
  match 'admin/search_users', :controller => 'admin', :action => 'search_users', :as => 'search_users'
  match 'admin/view_user_info', :controller => 'admin', :action => 'view_user_info', :as => 'view_user_info'
  match 'admin/recent_activity', :controller => 'admin', :action => 'view_recent_activity'

  # Faculty // Course Routes

  match 'course/show/:c_id', :controller => 'course', :action=>'show', :as => 'show_course'
  match 'course/edit/:id', :controller => 'course', :action => 'edit', :as => 'edit_course'
  match 'course/submit_edit', :controller => 'course', :action => 'submit_edit'
  match 'course/manage_groups/:id', :controller => 'course', :action => 'manage_groups'
  get "faculty/index"
  match 'faculty/index', :controller => 'faculty', :action => 'index', :as => 'faculty_index'
  match '/courses', :controller => 'faculty', :action => 'index', :as => 'course_index'
  match 'course/new', :controller => 'course', :action => 'new', :as => 'new_course'
  match 'course/create', :controller => 'course', :action => 'create', :as => 'create_course'
  match 'course/add_student', :controller => 'course', :action => 'add_student'
  
  # Assignment Routes
  get "assignment/index"
  match 'assignment', :controller => 'assignment', :action=> 'index'
  match 'assignments', :controller => 'assignment', :action=> 'index'
  match 'assignment/create/:course_id', :controller => 'assignment', :action => 'create' 
  match 'assignment/edit/:assignment_id', :controller => 'assignment', :action => 'edit' 
	match 'assignment/view/:assignment_id',:controller => 'assignment', :action => 'view', :as => 'assignment_view'
  match 'assignment/submit_new', :controller => 'assignment', :action => 'submit_new'
  match 'assignment/submitchanges', :controller =>'assignment', :action => 'submitchanges'
  match 'assignment/upload', :controller => 'assignment', :action => 'upload'
  match 'assignment/adminView/:assignment_id', :controller => 'assignment', :action => 'adminView'
  match 'assignment/download/:file_id', :controller => 'assignment', :action => 'download'
  match 'assignment/downloadAll/:assignment_id', :controller => 'assignment', :action => 'downloadAll'

  # Review Assignment Routes
  match 'reviewassignment/create/:assignment_id',:controller => 'review_assignment', :action => 'create'
  match 'reviewassignment/pairings',:controller => 'review_assignment', :action => 'pairings'
  match 'reviewassignment/pairings/:redo',:controller => 'review_assignment', :action => 'pairings'
  match 'reviewassignment/view/:id',:controller => 'review_assignment', :action => 'view'
  match 'reviewassignment/studentsubmit',:controller => 'review_assignment', :action => 'student_submit'
  match 'reviewassignment/viewsubmission/:mapping_id',:controller => 'review_assignment', :action => 'view_submission'
	match 'reviewassignment/:id/grades',:controller => 'review_assignment', :action => 'grades'
	match 'reviewassignment/:id/:pos/answer_form',:controller => 'review_assignment', :action => 'answer_form'
  match 'reviewassignment/edit/:id', :controller => 'review_assignment', :action => 'edit'
  match 'reviewassignment/view_feedback/:id' => 'review_assignment#view_feedback'
  match 'reviewassignment/submit_faculty_review/' => 'review_assignment#submit_faculty_review'
  
  # File Routes
  match 'files/delete/:file_id', :controller => 'file_submissions', :action => 'delete', :as => 'remove_file'
  match 'view_live/:file_id', :controller => 'file_submissions', :action => 'view_live', :as => 'view_live'


  #Redirect to 404 Page
  #This MUST be the last route
  match '*a', :to => 'errors#routing'
end

src/app/controllers/home_controller.rb
class HomeController < ApplicationController


  ## TODO DOCUMENT
  ## PURPOSE
  # [Route(s)]
  ## * TODO define routes
  # [Params]
  ## * TODO define params
  # [Environment Variables]
  ## * TODO define environment variables
  def index

  end


  ## TODO DOCUMENT
  ## PURPOSE
  # [Route(s)]
  ## * TODO define routes
  # [Params]
  ## * TODO define params
  # [Environment Variables]
  ## * TODO define environment variables
  def contact_us
  end


  ## TODO DOCUMENT
  ## PURPOSE
  # [Route(s)]
  ## * TODO define routes
  # [Params]
  ## * TODO define params
  # [Environment Variables]
  ## * TODO define environment variables
  def send_contact_email
    name = params[:user_name]
    subject = params[:comment_subject]
    comment = params[:comment_text]

    if comment == ''
      flash[:error] = 'Please enter content to the comment section before submitting. Thanks!'
    else
      Emailer.delay.file_complaint(name, subject, comment)
      flash[:notice] = 'Message received! Thank you very much for your feedback!'
    end
    redirect_to contact_us_path
  end

end

src/app/helpers/home_helper.rb
# EMPTY
module HomeHelper
end

src/app/views/home/_admin_home.html.erb
<% if current_user.admin? %>
  <%= render '/admin/users/recent_activity' %>




<% end %>

src/app/views/home/_faculty_home.html.erb
<% if current_user.faculty? %>

<% end %>

src/app/views/home/_student_home.html.erb
<% if current_user.student? %>

<% end %>

src/app/views/home/_ta_home.html.erb
<% if current_user.ta? %>

<% end %>

src/app/views/home/contact_us.html.erb
<h2>Contact Us</h2>

<%= form_tag send_contact_email_path, :id => 'add_students', :class => 'form-search' do %>
    <p>Help us improve or tell us what you like about CodeSwap!</p></br>
             <h4><strong>Name</strong> (optional)</h4>
                <%= text_field_tag 'user_name', '', :class => 'input-medium search-query' %>
             <h4><strong>Subject</strong></h4>
                <%= text_field_tag 'comment_subject', '', :class => 'input-medium search-query' %>
             <h4><strong>Comment</strong>:</h4>
                <%= text_area_tag 'comment_text', '', :class => 'input-large search-query' %>
<br/>
<br/>
    <%= submit_tag "Submit", :id => "submitter", :onClick => "disableElement('submitter')", :class => 'btn' %>

    <%= link_to 'Back', :back, :class => 'btn' %>
<% end %>

src/app/views/home/index.html.erb
<h3>Welcome to <%= image_tag("CodeSwapLogo.png", :width => "300px") %>!</h3>

<% unless current_user %>
  <h4>You should <u data-target="#logInModal" role="button" data-toggle="modal"><%= link_to "Sign in" %></u>!<h4>
<% else %>

<h4>Glad to have you here, <%= current_user.first_name %>!</h4>
<p>
  Our records indicate that you are a <strong><%= current_user.role %></strong>.</br>
</p>
  
<p>
<strong>Please Note</strong>: This site is a work in progress. What you see here today could still contain a variety of unresolved bugs. If you happen to stumble across anything that seems out of place, or have any questions, comments, concerns or ideas regarding the layout or functionality of a page (or the site as a whole), please do not hesitate to let us know by using the "Contact Us" link at the top of any page.
</p>

<p>
Thanks!</br>
-The CodeSwap Team
</p>

<% end %>