src/config/routes.rb
CodeSwap::Application.routes.draw do
  get "admin/index"

  resources :file_submissions
  resources :authentications
  resources :user
  devise_for :users, :controllers => { :registrations => 'registrations'}

  get "home/index"

  match 'contact_us', :controller => 'home', :action => 'contact_us', :as => 'contact_us'
  match 'send_contact_email', :controller => 'home', :action => 'send_contact_email', :as => 'send_contact_email'

  root :to => "home#index"

  match '/auth/:provider/callback' => 'authentications#create'

  match '/users/sign_up' => 'home#index'

  match "admin/create_faculty", :controller => 'admin', :action => 'create_faculty'
  match 'admin', :controller => 'admin', :action => 'index', :as => 'admin_path'
  match 'users', :controller => 'admin', :action => 'index', :as => 'view_users'
  match 'admin/add_user', :controller => 'admin', :action => 'add_user'
  match 'view_faculty', :controller => 'admin', :action => 'view_faculty', :as => 'view_faculty'
  match 'view_admin', :controller => 'admin', :action => 'view_admin', :as => 'view_admin'
  match 'view_students', :controller => 'admin', :action => 'view_students', :as => 'view_students'
  match 'admin/delete_user', :controller => 'admin', :action => 'delete_user'
  match 'admin/search_users', :controller => 'admin', :action => 'search_users', :as => 'search_users'
  match 'admin/view_user_info', :controller => 'admin', :action => 'view_user_info', :as => 'view_user_info'
  match 'admin/recent_activity', :controller => 'admin', :action => 'view_recent_activity'

  # Faculty // Course Routes

  match 'course/show/:c_id', :controller => 'course', :action=>'show', :as => 'show_course'
  match 'course/edit/:id', :controller => 'course', :action => 'edit', :as => 'edit_course'
  match 'course/submit_edit', :controller => 'course', :action => 'submit_edit'
  match 'course/manage_groups/:id', :controller => 'course', :action => 'manage_groups'
  get "faculty/index"
  match 'faculty/index', :controller => 'faculty', :action => 'index', :as => 'faculty_index'
  match '/courses', :controller => 'faculty', :action => 'index', :as => 'course_index'
  match 'course/new', :controller => 'course', :action => 'new', :as => 'new_course'
  match 'course/create', :controller => 'course', :action => 'create', :as => 'create_course'
  match 'course/add_student', :controller => 'course', :action => 'add_student'
  
  # Assignment Routes
  get "assignment/index"
  match 'assignment', :controller => 'assignment', :action=> 'index'
  match 'assignments', :controller => 'assignment', :action=> 'index'
  match 'assignment/create/:course_id', :controller => 'assignment', :action => 'create' 
  match 'assignment/edit/:assignment_id', :controller => 'assignment', :action => 'edit' 
	match 'assignment/view/:assignment_id',:controller => 'assignment', :action => 'view', :as => 'assignment_view'
  match 'assignment/submit_new', :controller => 'assignment', :action => 'submit_new'
  match 'assignment/submitchanges', :controller =>'assignment', :action => 'submitchanges'
  match 'assignment/upload', :controller => 'assignment', :action => 'upload'
  match 'assignment/adminView/:assignment_id', :controller => 'assignment', :action => 'adminView'
  match 'assignment/download/:file_id', :controller => 'assignment', :action => 'download'
  match 'assignment/downloadAll/:assignment_id', :controller => 'assignment', :action => 'downloadAll'

  # Review Assignment Routes
  match 'reviewassignment/create/:assignment_id',:controller => 'review_assignment', :action => 'create'
  match 'reviewassignment/pairings',:controller => 'review_assignment', :action => 'pairings'
  match 'reviewassignment/pairings/:redo',:controller => 'review_assignment', :action => 'pairings'
  match 'reviewassignment/view/:id',:controller => 'review_assignment', :action => 'view'
  match 'reviewassignment/studentsubmit',:controller => 'review_assignment', :action => 'student_submit'
  match 'reviewassignment/viewsubmission/:mapping_id',:controller => 'review_assignment', :action => 'view_submission'
	match 'reviewassignment/:id/grades',:controller => 'review_assignment', :action => 'grades'
	match 'reviewassignment/:id/:pos/answer_form',:controller => 'review_assignment', :action => 'answer_form'
  match 'reviewassignment/edit/:id', :controller => 'review_assignment', :action => 'edit'
  match 'reviewassignment/view_feedback/:id' => 'review_assignment#view_feedback'
  match 'reviewassignment/submit_faculty_review/' => 'review_assignment#submit_faculty_review'
  
  # File Routes
  match 'files/delete/:file_id', :controller => 'file_submissions', :action => 'delete', :as => 'remove_file'
  match 'view_live/:file_id', :controller => 'file_submissions', :action => 'view_live', :as => 'view_live'


  #Redirect to 404 Page
  #This MUST be the last route
  match '*a', :to => 'errors#routing'
end

src/app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :provider, :uid, :user_id
end

src/app/controllers/authentications_controller.rb
## Handles OpenAuth Integration
class AuthenticationsController < ApplicationController

  ## Used to view all open authentications
  # [Route(s)]
  ## * /authentications
  ## * /authentications/index
  # [Params]
  ## * None
  # [Environment Variables]
  ## * authentications - All authentications authorized by the current user
  def index
    @authentications = current_user.authentications if current_user
  end

  ## Associates an open auth account with the user.
  ## Magic.
  # [Route(s)]
  ## * /authentications/create
  # [Params]
  ## * None
  # [Environment Variables]
  ## * None
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    else
      if current_user
        current_user.authentications.create(:provider => omniauth['provider'], :uid => omniauth['uid'])
        flash[:notice] = "Authentication successful."
        redirect_to root_path
      else
        flash[:error] = "This " + omniauth['provider'] + " account is not linked yet. Please log in and link the account."
        redirect_to user_session_path
      end
    end
  end

  ## Disassociates an open authentication account with the current user.
  # [Route(s)]
  ## * /authentications/destroy/:id
  # [Params]
  ## * id - ID of the authentication to destroy
  # [Environment Variables]
  ## * authentication - instance of the destroyed authentication
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to user_session_path
  end
end

src/app/helpers/authentications_helper.rb
# EMPTY
module AuthenticationsHelper
end

src/app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/authentications/_links.html.erb
<!DOCTYPE html>

<% if !current_user %>
<p><strong>Sign in through one of these services:</strong></p>
<% elsif !current_user.authentications.empty? %>
   <p><strong>Add another service to sign in with:</strong></p>
<% else %>
   <p><strong>Add a service to sign in with:</strong></p>
<% end %>


<% if (current_user and current_user.authentications.where(:provider => "twitter").empty?) or !current_user%>
<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "icons/twitter_32.png", :size => "32x32", :alt => "Twitter" %>Twitter</a>
<% end %>


<% if (current_user and current_user.authentications.where(:provider => "facebook").empty?) or !current_user%>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "icons/facebook_32.png", :size => "32x32", :alt => "Facebook" %>Facebook</a>
<% end %>

<% if (current_user and current_user.authentications.where(:provider => "google").empty?) or !current_user%>
<a href="/auth/google_apps" class="auth_provider">
  <%= image_tag "icons/google_32.png", :size => "32x32", :alt => "Google" %>Google</a>

<% end %>
<% if (current_user and current_user.authentications.where(:provider => "openid").empty?) or !current_user%>
<a href="/auth/open_id" class="auth_provider">
  <%= image_tag "icons/openid_32.png", :size => "32x32", :alt => "OpenID" %>OpenID</a>
<div class="clear"></div>

<% end %>

src/app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

src/app/views/authentications/index.html.erb
<!DOCTYPE html>
<% if @authentications %>
 <% unless @authentications.empty? %>
  <p><strong>You can sign in to this account using:</strong></p>
   <div class="authentications">
    <% for authentication in @authentications %>
     <div class="authentication">
      <%= image_tag "icons/#{authentication.provider}_32.png", :size => "32x32" %>
      <div class="provider"><%= authentication.provider.titleize %></div>
      <div class="uid"><%= authentication.uid %></div>
       <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
     </div>
     <% end %>
     <div class="clear"></div>
    </div>
   <% end %>
<% end %>

<%= render "links" %>

src/app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

src/app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>